#!/bin/bash
# Securthy Scanner — Installer
# Client: %%CLIENT_NAME%%
# Generated by Securthy Platform

set -e

INSTALL_DIR="/opt/securthy"
BIN_DIR="/usr/local/bin"
PLATFORM_URL="%%PLATFORM_URL%%"
CLIENT_API_KEY="%%CLIENT_API_KEY%%"

# Find Go binary
GO_BIN=""
for p in /usr/local/go/bin/go /usr/bin/go /usr/local/bin/go $(which go 2>/dev/null); do
    if [ -f "$p" ]; then
        GO_BIN="$p"
        break
    fi
done

if [ -z "$GO_BIN" ]; then
    echo "[!] Go not found. Installing..."
    apt-get update -q && apt-get install -y golang-go
    GO_BIN=$(which go)
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Securthy Scanner — Installation                      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "[*] Platform : $PLATFORM_URL"
echo "[*] Go       : $GO_BIN"
echo "[*] Install  : $INSTALL_DIR"
echo ""

mkdir -p "$INSTALL_DIR"
cp -r . "$INSTALL_DIR/"
cd "$INSTALL_DIR"

echo "[*] Installing dependencies..."
$GO_BIN mod tidy 2>/dev/null || true

# Build-time flags — bake platform URL and API key into the scanner
LDFLAGS="-X main.PlatformURL=$PLATFORM_URL -X main.ClientAPIKey=$CLIENT_API_KEY"
GUI_LDFLAGS="-X main.PlatformURL=$PLATFORM_URL"

echo "[*] Building scanner binaries..."
$GO_BIN build -ldflags "$LDFLAGS"     -o scanner_bin       ./cmd/            && echo "  [+] scanner_bin"
$GO_BIN build                          -o employee_bin      ./employee/        && echo "  [+] employee_bin"
$GO_BIN build                          -o employee_packs_bin ./employee_packs/ && echo "  [+] employee_packs_bin"
$GO_BIN build -ldflags "$LDFLAGS"     -o api_bin           ./api/             && echo "  [+] api_bin"
$GO_BIN build -ldflags "$GUI_LDFLAGS" -o securthy          ./gui/             && echo "  [+] securthy (GUI)"

# NOTE: packs_bin is NOT built here.
# It is a separate purchase — download it from your dashboard after buying a pack.
echo ""
echo "  [i] packs_bin is NOT included in this installer."
echo "      Purchase a remediation pack from your dashboard to get it."

# Install CLI command
cat > "$BIN_DIR/securthy" << 'LAUNCHER'
#!/bin/bash
cd /opt/securthy
exec ./securthy "$@"
LAUNCHER
chmod +x "$BIN_DIR/securthy"

# Desktop shortcut
if [ -d "/usr/share/applications" ]; then
    cat > /usr/share/applications/securthy.desktop << 'DESKTOP'
[Desktop Entry]
Name=Securthy Scanner
Comment=Healthcare Network Security Assessment
Exec=bash -c "cd /opt/securthy && ./securthy"
Terminal=true
Type=Application
Categories=Network;Security;
DESKTOP
    echo "  [+] Desktop shortcut created"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Scanner Installation Complete!                       ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║                                                         ║"
echo "║   1. Run:  securthy                                     ║"
echo "║   2. Choose option 3 — Full Assessment                  ║"
echo "║   3. Results will appear on your dashboard at:          ║"
echo "║      $PLATFORM_URL"
echo "║                                                         ║"
echo "║   To apply fixes after purchasing a pack:               ║"
echo "║   Download packs_bin from your dashboard and run it.    ║"
echo "║                                                         ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
