package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

// ── Build-time variables — set by platform when generating packs_bin ─────────
// go build -ldflags "-X main.PlatformURL=... -X main.LicenseKey=... -X main.AllowedTier=essentiel"
var (
	PlatformURL  = "http://localhost:8000"
	LicenseKey   = "" // baked in at build time per purchase
	AllowedTier  = "" // essentiel | securite | conformite — baked in
	ClientAPIKey = "" // client's API key
)

func main() {
	// Parse flags
	targetFile := ""
	winUser    := "Administrator"
	winPass    := ""
	sshUser    := "root"
	sshKey     := ""
	sshPass    := ""
	sshPort    := 0
	demoMode   := false

	for _, arg := range os.Args[1:] {
		switch {
		case arg == "--demo":
			demoMode = true
		case strings.HasPrefix(arg, "--targets="):
			targetFile = strings.TrimPrefix(arg, "--targets=")
		case strings.HasPrefix(arg, "--win-user="):
			winUser = strings.TrimPrefix(arg, "--win-user=")
		case strings.HasPrefix(arg, "--win-pass="):
			winPass = strings.TrimPrefix(arg, "--win-pass=")
		case strings.HasPrefix(arg, "--ssh-user="):
			sshUser = strings.TrimPrefix(arg, "--ssh-user=")
		case strings.HasPrefix(arg, "--ssh-key="):
			sshKey = strings.TrimPrefix(arg, "--ssh-key=")
		case strings.HasPrefix(arg, "--ssh-pass="):
			sshPass = strings.TrimPrefix(arg, "--ssh-pass=")
		case strings.HasPrefix(arg, "--ssh-port="):
			sshPort, _ = strconv.Atoi(strings.TrimPrefix(arg, "--ssh-port="))
		}
	}

	// ── License check ─────────────────────────────────────────────────────────
	// AllowedTier is baked in at build time by the platform.
	// If empty, this binary was not generated by the platform.
	if AllowedTier == "" {
		fmt.Println()
		fmt.Println("  ┌─────────────────────────────────────────────────────────┐")
		fmt.Println("  │  THIS BINARY HAS NO LICENSE                             │")
		fmt.Println("  │                                                         │")
		fmt.Println("  │  Download packs_bin from your Securthy dashboard        │")
		fmt.Println("  │  after purchasing a remediation pack.                   │")
		fmt.Println("  │                                                         │")
		fmt.Println("  │  Each packs_bin is generated specifically for you       │")
		fmt.Println("  │  with your tier and API key baked inside.               │")
		fmt.Println("  └─────────────────────────────────────────────────────────┘")
		fmt.Println()
		os.Exit(1)
	}

	tier := AllowedTier
	fmt.Println()
	fmt.Printf("  [✓] License valid — Pack %s unlocked\n", strings.ToUpper(tier))
	if LicenseKey != "" {
		fmt.Printf("  [✓] License key   : %s\n", LicenseKey)
	}
	fmt.Println()

	// ── Load targets ──────────────────────────────────────────────────────────
	targets, err := loadTargets(targetFile)
	if err != nil {
		fmt.Println("[!] Could not load targets:", err)
		fmt.Println("    Run the scanner first to generate targets.json")
		os.Exit(1)
	}

	if targets.RecommendedTier != "" && targets.RecommendedTier != tier {
		fmt.Printf("  [!] Scanner recommended '%s' but you purchased '%s'\n",
			strings.ToUpper(targets.RecommendedTier), strings.ToUpper(tier))
		fmt.Printf("  [!] ISO Score was %d/100 — %s\n\n",
			targets.ISOScore, targets.ISOGrade)
	}

	printBanner(tier, targets)

	winCreds := WinCreds{User: winUser, Pass: winPass}
	sshCreds := SSHCreds{User: sshUser, KeyPath: sshKey, Port: sshPort, Pass: sshPass}

	log := NewRunLog()

	if demoMode {
		runDemoMode(targets, tier, log)
	} else {
		switch strings.ToLower(tier) {
		case "essentiel":
			RunEssentiel(targets, winCreds, sshCreds, log)
		case "securite":
			RunSecurite(targets, winCreds, sshCreds, log)
		case "conformite":
			RunConformite(targets, winCreds, sshCreds, log)
		default:
			fmt.Println("[!] Unknown tier:", tier)
			os.Exit(1)
		}
	}

	log.PrintSummary()
	log.SaveReport(fmt.Sprintf("pack_report_%d.json", time.Now().Unix()))

	// ── Notify platform that pack was applied ─────────────────────────────────
	notifyPlatform(tier, log)
}

func notifyPlatform(tier string, log *RunLog) {
	if PlatformURL == "" || ClientAPIKey == "" {
		return
	}

	passed, failed := 0, 0
	for _, r := range log.Results {
		if r.Success {
			passed++
		} else {
			failed++
		}
	}

	fmt.Printf("\n[*] Notifying platform of pack application...\n")
	fmt.Printf("    Pack: %s | Fixes: %d succeeded, %d failed\n",
		strings.ToUpper(tier), passed, failed)
	// In production: POST to platform API with results
	// This updates the ISO score_after on the dashboard
}

func runDemoMode(targets *Targets, tier string, log *RunLog) {
	fmt.Println("  [DEMO MODE] Simulating remediation on hospital network...")
	fmt.Println("  (In production this connects via SSH/WinRM to real machines)")
	fmt.Println()

	allHosts := append(targets.Linux, targets.Windows...)
	if len(allHosts) == 0 {
		fmt.Println("  No hosts in targets.json — run the scanner first")
		return
	}

	demoFixes := map[string][]string{
		"essentiel": {
			"disable-smbv1", "enable-rdp-nla", "disable-telnet",
			"firewall-rules", "remove-snmp-public",
		},
		"securite": {
			"disable-smbv1", "enable-rdp-nla", "disable-telnet",
			"firewall-rules", "remove-snmp-public", "enable-smb-signing",
			"snmpv3-upgrade", "tls-hl7", "tls-dicom", "fhir-auth",
		},
		"conformite": {
			"disable-smbv1", "enable-rdp-nla", "disable-telnet",
			"firewall-rules", "remove-snmp-public", "enable-smb-signing",
			"snmpv3-upgrade", "tls-hl7", "tls-dicom", "fhir-auth",
			"harden-ssh", "install-fail2ban",
		},
	}

	fixes := demoFixes[strings.ToLower(tier)]
	if fixes == nil {
		fixes = demoFixes["essentiel"]
	}

	for _, host := range allHosts {
		fmt.Printf("  [HOST] %s\n", host)
		for _, fix := range fixes {
			fmt.Printf("  [✓] %-16s %-35s  [SIMULATED]\n", host, fix)
			log.Add(host, fix, "demo", true, "simulated fix applied", "")
		}
		fmt.Println()
	}
}

func printBanner(tier string, targets *Targets) {
	fmt.Println()
	fmt.Println("╔══════════════════════════════════════════════════════════╗")
	fmt.Printf("║   Securthy DZ — Pack %-30s      ║\n", strings.ToUpper(tier))
	fmt.Println("╠══════════════════════════════════════════════════════════╣")
	fmt.Printf("║   Windows hosts : %-5d                                  ║\n", len(targets.Windows))
	fmt.Printf("║   Linux hosts   : %-5d                                  ║\n", len(targets.Linux))
	if targets.ISOScore > 0 {
		fmt.Printf("║   ISO Score     : %-3d/100 — %-28s  ║\n",
			targets.ISOScore, targets.ISOGrade)
	}
	fmt.Println("╚══════════════════════════════════════════════════════════╝")
	fmt.Println()
	fmt.Println("  WARNING: This will modify system configurations.")
	fmt.Println("  Ensure you have written authorization from the client.")
	fmt.Println()
	fmt.Print("  Continue? [y/N]: ")
	var confirm string
	fmt.Scanln(&confirm)
	if strings.ToLower(confirm) != "y" {
		fmt.Println("Aborted.")
		os.Exit(0)
	}
	fmt.Println()
}

func printUsage() {
	fmt.Println(`
Securthy DZ — Remediation Pack Engine

This binary is generated by the Securthy platform after purchasing a pack.
The tier and license are baked inside — no flags needed.

Usage:
  ./packs_bin --targets=targets.json --ssh-key=~/.ssh/id_rsa
  ./packs_bin --targets=targets.json --ssh-key=~/.ssh/id_rsa --ssh-port=2222
  ./packs_bin --demo   (simulate without real SSH)

Flags:
  --targets=     Path to targets.json (generated by scanner)
  --win-user=    Windows admin username (default: Administrator)
  --win-pass=    Windows admin password
  --ssh-user=    Linux SSH username (default: root)
  --ssh-key=     Path to SSH private key
  --ssh-pass=    SSH password (alternative to key)
  --ssh-port=    SSH port (default: 22)
  --demo         Simulate fixes without real SSH/WinRM

Download packs_bin from: ` + PlatformURL + `
`)
}
